name: Check and Update JSON Data

on:
  schedule:
    - cron: '0 1 * * *' # Menjalankan setiap hari pada jam 01:00 UTC
  workflow_dispatch:

jobs:
  check-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch the latest JSON data
      run: curl -o new_data.json https://tiara0404.github.io/api/api.json

    - name: Compare JSON files
      id: json_diff
      run: |
        if ! cmp -s new_data.json data.json; then
          mv new_data.json data.json
          echo "updated=true" >> $GITHUB_ENV
        else
          echo "updated=false" >> $GITHUB_ENV
        fi

    - name: Pull latest changes
      if: env.updated == 'true'
      run: git pull origin main

    - name: Update JSON if changed
      if: env.updated == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data.json
        git commit -m "Update JSON data from BPS"
        git push origin main
